"""Add ReviewReport and ScoringReport

Revision ID: 47ace6ac701b
Revises: 
Create Date: 2026-02-16 21:37:09.315350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47ace6ac701b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _array_type(item_type):  # noqa: ANN001
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        return postgresql.ARRAY(item_type)
    return sa.JSON()


_BOOTSTRAP_TABLES = {
    "completed_bid",
    "project",
    "provider_profile",
    "review_report",
    "scoring_report",
    "audit_log",
    "document",
    "project_model_policy",
}


def _is_bootstrapped_schema() -> bool:
    """Return true when the schema was already created outside Alembic."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing = set(inspector.get_table_names())
    return _BOOTSTRAP_TABLES.issubset(existing)


def upgrade() -> None:
    """Upgrade schema."""
    if _is_bootstrapped_schema():
        print("legacy schema already bootstrapped, skipping initial create_table batch")  # noqa: T201
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_bid',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=True),
    sa.Column('project_name', sa.Text(), nullable=False),
    sa.Column('engineering_category', sa.Text(), nullable=True),
    sa.Column('tenderer', sa.Text(), nullable=True),
    sa.Column('bid_result', sa.Text(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('file_info', sa.Text(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry_tag', sa.Text(), nullable=True),
    sa.Column('customer_tag', sa.Text(), nullable=True),
    sa.Column('sensitivity', sa.Enum('PUBLIC_OK', 'SENSITIVE', name='sensitivity_level'), nullable=False),
    sa.Column('token_budget_total', sa.Integer(), nullable=False),
    sa.Column('token_budget_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.Enum('PROJECT', 'USER', 'TENANT', name='provider_scope'), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('default_model', sa.Text(), nullable=False),
    sa.Column('key_storage', sa.Enum('ENCRYPTED_DB', 'TEMP_REDIS', 'VAULT', name='key_storage'), nullable=False),
    sa.Column('key_secret_ref', sa.Text(), nullable=False),
    sa.Column('encrypted_key', sa.LargeBinary(), nullable=True),
    sa.Column('allowed_tasks', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_report',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('section_key', sa.Text(), nullable=False),
    sa.Column('outline_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoring_report',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('score_total', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('TENDER', 'CLARIFICATION', 'EXPERT', 'AWARD', name='doc_kind'), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('object_uri', sa.Text(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('sensitivity', sa.Enum('PUBLIC_OK', 'SENSITIVE', name='sensitivity_level'), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='job_status'), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('output_doc_object_uri', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_model_policy',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('extract_profile_id', sa.UUID(), nullable=True),
    sa.Column('generate_profile_id', sa.UUID(), nullable=True),
    sa.Column('review_profile_id', sa.UUID(), nullable=True),
    sa.Column('embed_profile_id', sa.UUID(), nullable=True),
    sa.Column('query_rewrite_profile_id', sa.UUID(), nullable=True),
    sa.Column('program_support_profile_id', sa.UUID(), nullable=True),
    sa.Column('enable_review', sa.Boolean(), nullable=False),
    sa.Column('token_budget_total', sa.Integer(), nullable=False),
    sa.Column('token_budget_used', sa.Integer(), nullable=False),
    sa.Column('concurrency_limits', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['embed_profile_id'], ['provider_profile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['extract_profile_id'], ['provider_profile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generate_profile_id'], ['provider_profile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_support_profile_id'], ['provider_profile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_rewrite_profile_id'], ['provider_profile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_profile_id'], ['provider_profile.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('doc_block',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('block_type', sa.Text(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('section_anchor', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expert_doc',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('doc_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('industry_tag', sa.Text(), nullable=True),
    sa.Column('section_type', sa.Text(), nullable=True),
    sa.Column('sensitivity', sa.Enum('PUBLIC_OK', 'SENSITIVE', name='sensitivity_level'), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('forbidden_tags', _array_type(sa.Text()), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['document.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingest_job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='job_status'), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['document.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_call_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('version_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('provider_profile_id', sa.UUID(), nullable=True),
    sa.Column('evidence_ids', _array_type(sa.UUID()), nullable=False),
    sa.Column('prompt_hash', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('budget_remaining', sa.Integer(), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('fallback_count', sa.Integer(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('pricing_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_profile_id'], ['provider_profile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['generation_version.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('requirement_code', sa.Text(), nullable=False),
    sa.Column('strength', sa.Enum('MUST', 'SCORE', 'FORMAT', 'OTHER', name='requirement_strength'), nullable=False),
    sa.Column('score_weight', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('location_document_id', sa.UUID(), nullable=True),
    sa.Column('location_page_no', sa.Integer(), nullable=True),
    sa.Column('location_anchor', sa.Text(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('deliverables', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('parent_section_id', sa.UUID(), nullable=True),
    sa.Column('section_key', sa.Text(), nullable=False),
    sa.Column('section_title', sa.Text(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('requirement_codes', _array_type(sa.String()), nullable=False),
    sa.Column('evidence_ids', _array_type(sa.UUID()), nullable=False),
    sa.Column('origin', sa.Enum('AI', 'HUMAN', 'MERGE', name='section_origin'), nullable=False),
    sa.Column('edit_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('has_placeholders', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_section_id'], ['section_content.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['generation_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_analysis_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_matrix',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('SUPPORTED', 'NEED_HUMAN_INPUT', 'NOT_FOUND', name='matrix_status'), nullable=False),
    sa.Column('planned_section', sa.Text(), nullable=True),
    sa.Column('evidence_ids', _array_type(sa.UUID()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_chunk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expert_doc_id', sa.UUID(), nullable=False),
    sa.Column('chunk_no', sa.Integer(), nullable=False),
    sa.Column('excerpt_text', sa.Text(), nullable=False),
    sa.Column('excerpt_hash', sa.Text(), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('source_locator', sa.JSON(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('sensitivity_level', sa.Enum('PUBLIC_OK', 'SENSITIVE', name='sensitivity_level'), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('forbidden_tags', _array_type(sa.Text()), nullable=False),
    sa.Column('qdrant_point_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expert_doc_id'], ['expert_doc.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section_revision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_section_id', sa.UUID(), nullable=False),
    sa.Column('rev_no', sa.Integer(), nullable=False),
    sa.Column('editor', sa.Text(), nullable=False),
    sa.Column('patch_diff', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['base_section_id'], ['section_content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_key_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('BIDDING_POINTS', 'SCORING_POINTS', 'COMPLIANCE_REQUIREMENTS', 'BONUS_POINTS', 'RISK_ALERTS', name='tender_key_category'), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('section_anchor', sa.Text(), nullable=True),
    sa.Column('score_weight', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_must', sa.Boolean(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['tender_analysis_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tender_key_info')
    op.drop_table('section_revision')
    op.drop_table('evidence_chunk')
    op.drop_table('compliance_matrix')
    op.drop_table('tender_analysis_run')
    op.drop_table('section_content')
    op.drop_table('requirement')
    op.drop_table('llm_call_log')
    op.drop_table('ingest_job')
    op.drop_table('expert_doc')
    op.drop_table('doc_block')
    op.drop_table('project_model_policy')
    op.drop_table('generation_version')
    op.drop_table('document')
    op.drop_table('audit_log')
    op.drop_table('scoring_report')
    op.drop_table('review_report')
    op.drop_table('provider_profile')
    op.drop_table('project')
    op.drop_table('completed_bid')
    # ### end Alembic commands ###
